### ISSUE TITLE
Position documentation update needed.

### ISSUE THREAD

**Issue by larrybabb** [tnavatar/clingen-data-model#149] opened 2015-09-03 18:30 UTC
The refactoring related to issue 143 (intronOffset) caused the model within the conceptual/resource AlleleInstance to change significantly. The documentation needs to be updated to reflect the change.

**Comment by cbizon** [comment] 2015-09-16 14:22
this is a duplicate of 152.   Closing

**Closed as completed** 2015-09-16 14:23 UTC
Labels: help wanted, model
